services:
  - type: web
    name: rag-api
    env: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}
    envVars:
      - key: OPEN_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DB_PATH
        value: /tmp/rag_app.db
